# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift', '= 10.1.4'
  pod 'SwiftLint'

  target 'RChatTests' do
    inherit! :search_paths
    pod 'RealmSwift', '= 10.1.4'
    pod 'SwiftLint'
  end

  target 'RChatUITests' do
    pod 'RealmSwift', '= 10.1.4'
    pod 'SwiftLint'
  end

end
