# Uncomment the next line to define a global platform for your project
platform :ios, '14.2'

target 'RChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RChat
  pod 'SwiftLint'

  target 'RChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RChatUITests' do
    # Pods for testing
  end

end
